name: tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: pytorch/pytorch:1.10.0-cuda11.3-cudnn8-runtime

    steps:
    - uses: actions/checkout@v2

    - name: Update base dependencies
      run: |
        apt-get update && apt-get install -y build-essential
        apt-get install -y libsndfile1 make

    - name: Install dependencies
      id: chrispnet-wheel
      run:  |
        # install test requirements
        bash reinstall.sh

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .
      continue-on-error: true

    - name: Run Tests
      run: |
        bash test/test.sh