name: tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: pytorch/pytorch:1.10.0-cuda11.3-cudnn8-runtime

    steps:
    - uses: actions/checkout@v2

    - name: Update base dependencies
      run: |
        apt-get update && apt-get install -y build-essential
        apt-get install -y libsndfile1 make

    - name: Install dependencies
      id: chrispnet-wheel
      run:  |
        # install test requirements
        pip install -r requirements/requirements_test.txt
        # Build chrispnet as a wheel
        pip install build
        python -m build --no-isolation --wheel
        # Preserve wheel location
        DIST_FILE=$(find ./dist -name "*.whl" | head -n 1)
        echo "::set-output name=DIST_FILE::${DIST_FILE}" 

    - name: Install git lfs
      run: |
        sudo apt-get install -y git-lfs

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .
      continue-on-error: true
      
    - name: Run Tests
      shell: bash
      run: |
        pytest test/modules/encoder/test_conformer_encoder_nemo.py